#!/usr/bin/env bash
# This script traps SIGTERM and prints a message

trap 'echo "I am invincible!!!"' SIGTERM

# Keep the script running to be able to receive signals
while true; do
    sleep 1
done
