#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL

# Find the PID of the 7-highlander process
PID=$(pgrep -f 7-highlander)

# Kill it with signal 9 (SIGKILL)
kill -9 "$PID"
