#!/usr/bin/env bash
# This script displays the content of current directory, showing only the part after the first dash

for file in *
do
    if [[ "$file" != .* ]]
    then
        if [[ "$file" == *-* ]]
        then
            echo "${file#*-}"
        else
            echo "$file"
        fi
    fi
done
