#!/usr/bin/env bash
# This script checks properties of the file named 'school' and prints appropriate messages

if [ -e "school" ]; then
  if [ -d "school" ]; then
    echo "school exists but it’s a directory"
  elif [ -f "school" ]; then
    if [ ! -s "school" ]; then
      echo "school exists but empty"
    else
      echo "File exist and is a regular file"
    fi
  fi
else
  echo "school doesn’t exist"
fi
